name: PR workflow

on: 
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  kafka-topic-config-validator:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      issues: read
    name: workflow
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
         fetch-depth: '0'

      - run: echo "true"

      - name: PR review Comment
        run: |
            gh api \
              --method POST \
              -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              /repos/red-eyes-22/kafka-topics/pulls/${{ github.event.number }}/reviews \
              -f body="abc" \
              -f event='REQUEST_CHANGES' 
        env:
          GH_TOKEN: ${{ github.token }}
